### ISSUE TITLE
clearInterval on unmount

### ISSUE THREAD

**Issue by OleksiiKachan** [inlightmedia/react-countdown-timer#1]
I have memory leak when unmount component that has the countdown timer. Interval is still running but component is not there anymore.
Why don't you clear interval in useEffect return statement

**Comment by inlightmedia** [comment]
Thanks Oleksii, I'll have a look!

**Comment by inlightmedia** [comment]
Looks like I forgot, thanks for finding this! All fixed.

**Comment by OleksiiKachan** [comment]
@inlightmedia can you release new version please?

**Comment by inlightmedia** [comment]
Should be up now, enjoy!
